version: "3.8"
services:
  app-web:
    platform: linux/amd64
    container_name: app-dev
    image: app-dev
    build:
      context: .
    volumes:
      - ./src:/app/src
    ports:
      - 3000:3000

